### ISSUE TITLE
toggle audio and video

### ISSUE THREAD

**Issue by galileomd** [Mahabali/Apprtc-swift#5]
so is toggleAudioMute() and toggleVideoMute() taken out of the webrtc lib now?  how's audio and video now toggled?

**Comment by dhilip-payoda** [comment]
I missed the muting part. Thanks for reminder. Stream muting is a custom implementation. Refer ARDAppClient class. Now closing this issue.

**Comment by Mahabali** [comment]
I missed the muting part. Thanks for reminder. Stream muting is a custom implementation. Refer ARDAppClient class. Now closing this issue.

**Comment by galileomd** [comment]
hmm now not compiling right... i made sure to clean out prior builds..  any suggestions?

![screen shot 2016-12-10 at 9 33 05 am](https://cloud.githubusercontent.com/assets/9544064/21074000/c7be4e3c-bebb-11e6-9fcd-6eef5d201e31.png)

**Comment by Mahabali** [comment]
Can you recheck by cleaning the project. I dont have compilation error.

**Comment by galileomd** [comment]
weird.. i deleted entire lib folder and recopied things over, now working!
